version: '3.3'
services:
  mysql-docker-compose:
    image: ubuntu/mysql
    restart: always
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '30306:3306'
    expose:
      # Opens port 30306 on the container
      - '30306'
  
  backend-container:
    build: ./APIODKPointage
    ports:
      - 8000:8080
    depends_on:
      - mysql-docker-compose
  
  frontend-container:
    build: ./newOdkpointage
    ports:
      - 9000:80
    depends_on:
      - backend-container